{
 "title": "Backend Benchmark",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Host Network I/O (eth0)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{id=\"/\", interface=\"eth0\"}[1m])",
     "legendFormat": "{{RX}}"
    },
    {
     "expr": "  rate(container_network_transmit_bytes_total{id=\"/\", interface=\"eth0\"}[1m])",
     "legendFormat": "{{TX}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "  container_memory_working_set_bytes{id=~\"/docker/.+\"} / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{id=~\"/docker/.+\"}[1m]) * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}